language: java
before_install:
 - chmod +x gradlew
deploy:
   provider: releases
   api_key:
     secure:  463388fb214385df190ec20e2432a07226869ec1 
   file: 
     - TriggerReactor.jar
   skip_cleanup: true
   on:
     branch: master