language: java
before_install:
 - chmod +x gradlew
script: 
 - ./gradlew check
 - ./gradlew build
deploy:
   provider: releases
   api_key: $githubkey
   file: build/libs/TriggerReactor.jar
   skip_cleanup: true
   on:
     tags: true
     branch: 
       - master
       - development
       