language: java
before_install:
 - chmod +x gradlew
deploy:
   provider: releases
   api_key: $githubkey
   file: 
     - TriggerReactor.jar
   skip_cleanup: true
   on:
     tags: true
     branch: 
       - master
       - development