name: TriggerReactor
main: io.github.wysohn.triggerreactor.main.TriggerReactor
version: 1.0.3
author: wysohn
softdepend: [Vault, PlaceholderAPI, mcMMO, TheGuild, Factions, CoreProtect]
commands:
  triggerreactor:
    aliases: [trigger, trg]
    description: trigger reactor
permissions:
  triggerreactor.admin:
    description: Grants access to commands