name: TriggerReactor
main: io.github.wysohn.triggerreactor.main.TriggerReactor
version: 1.0.2
author: wysohn
softdepend: [Vault, PlaceHolderAPI, mcMMO, TheGuild]
commands:
  triggerreactor:
    aliases: [trigger, trg]
    description: trigger reactor
permissions:
  triggerreactor.admin:
    description: Grants access to commands