name: TriggerReactor
main: io.github.wysohn.triggerreactor.main.TriggerReactor
version: 0.1.6
author: wysohn
softdepend: [ChatLib, UserInterfaceLib, SkillsLib, Vault, PlaceHolderAPI]
commands:
  triggerreactor:
    aliases: [trigger, trg]
    description: trigger reactor
permissions:
  triggerreactor.admin:
    description: Grants access to commands