name: TriggerReactor
main: io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor
version: 1.1.6
author: wysohn
authors: [soliddanii]
softdepend: [Vault, PlaceholderAPI, mcMMO, TheGuild, Factions, CoreProtect, ProtocolLib]
commands:
  triggerreactor:
    aliases: [trigger, trg]
    description: trigger reactor
permissions:
  triggerreactor.admin:
    description: Grants access to commands